## Auto generated by useShinyCellModular

message("Starting ShinyCellModular modular app")

library(shiny)
library(shinyhelper)
library(shinyjs)
library(data.table)
library(Matrix)
library(DT)
library(magrittr)
library(ggplot2)
library(ggrepel)
library(hdf5r)
library(ggdendro)
library(gridExtra)
library(arrow)
library(shinythemes)
library(shinydashboard)
library(tidyverse)
library(sortable)
library(plotly)
library(FlexDotPlot) #devtools::install_github("Simon-Leonard/FlexDotPlot")
library(RColorBrewer)
library(ggforce)
library(limma) #BiocManager::install("limma")
library(edgeR) #BiocManager::install("edgeR")
library(ggseqlogo)


### Useful stuff 
# Colour palette 
cList = list(c("grey85","#FFF7EC","#FEE8C8","#FDD49E","#FDBB84", 
               "#FC8D59","#EF6548","#D7301F","#B30000","#7F0000"), 
             c("#4575B4","#74ADD1","#ABD9E9","#E0F3F8","#FFFFBF", 
               "#FEE090","#FDAE61","#F46D43","#D73027")[c(1,1:9,9)], 
             c("#FDE725","#AADC32","#5DC863","#27AD81","#21908C", 
               "#2C728E","#3B528B","#472D7B","#440154")) 
names(cList) = c("White-Red", "Blue-Yellow-Red", "Yellow-Green-Purple") 
 
# Panel sizes 
pList = c("400px", "600px", "800px") 
names(pList) = c("Small", "Medium", "Large") 
pList2 = c("500px", "700px", "900px") 
names(pList2) = c("Small", "Medium", "Large") 
pList3 = c("600px", "800px", "1000px") 
names(pList3) = c("Small", "Medium", "Large") 
sList = c(18,24,30) 
names(sList) = c("Small", "Medium", "Large") 
lList = c(5,6,7) 
names(lList) = c("Small", "Medium", "Large") 
 
# Function to extract legend 
g_legend <- function(a.gplot){  
  tmp <- ggplot_gtable(ggplot_build(a.gplot))  
  leg <- which(sapply(tmp$grobs, function(x){x$name}) == "guide-box")  
  legend <- tmp$grobs[[leg]]  
  legend 
}  
 
# Plot theme 
sctheme <- function(base_size = 24, XYval = TRUE, Xang = 0, XjusH = 0.5){ 
  oupTheme = theme( 
    text =             element_text(size = base_size, family = "Helvetica"), 
    panel.background = element_rect(fill = "white", colour = NA), 
    axis.line =   element_line(colour = "black"), 
    axis.ticks =  element_line(colour = "black", size = base_size / 20), 
    axis.title =  element_text(face = "bold"), 
    axis.text =   element_text(size = base_size), 
    axis.text.x = element_text(angle = Xang, hjust = XjusH), 
    legend.position = "bottom", 
    legend.key =      element_rect(colour = NA, fill = NA) 
  ) 
  if(!XYval){ 
    oupTheme = oupTheme + theme( 
      axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
      axis.text.y = element_blank(), axis.ticks.y = element_blank()) 
  } 
  return(oupTheme) 
} 
 
app_title <- "Example ShinyCellModular - Single Cell RNAseq"

dir_inputs <- "/mnt/ceph/mbp/servers/bioinformatics-platform/home/lper0012/ShinyCellModular/example_apps/app_scRNAseq/"

sc1conf <- readRDS(file.path(dir_inputs, "sc1conf.rds"))
sc1def  <- readRDS(file.path(dir_inputs, "sc1def.rds"))
sc1gene <- readRDS(file.path(dir_inputs, "sc1gene.rds"))
sc1meta <- readRDS(file.path(dir_inputs, "sc1meta.rds"))

# there must be a better way to do this for all alternative assays

if (file.exists(file.path(dir_inputs,"ATAC"))) {
  atac_dir         <- file.path(dir_inputs, "ATAC")
  sc1conf_atac     <- tryCatch({readRDS(file.path(atac_dir, "sc1conf.rds"))},error = function(e) {return(NULL)})
  sc1def_atac      <- tryCatch({readRDS(file.path(atac_dir, "sc1def.rds"))},error = function(e){return(NULL)})
  sc1gene_atac     <- tryCatch({readRDS(file.path(atac_dir, "sc1gene.rds"))},error = function(e){return(NULL)})
  sc1meta_atac     <- tryCatch({readRDS(file.path(atac_dir, "sc1meta.rds"))},error = function(e){return(NULL)})
  sc1fragmentpaths <- tryCatch({readRDS(file.path(atac_dir, "sc1fragmentpaths.rds"))},error = function(e){return(NULL)})
  sc1annotation    <- tryCatch({readRDS(file.path(atac_dir, "sc1annotation.rds"))},error = function(e){return(NULL)})
  sc1peaks         <- tryCatch({readRDS(file.path(atac_dir, "sc1peaks.rds"))},error = function(e){return(NULL)})
  sc1links         <- tryCatch({readRDS(file.path(atac_dir, "sc1links.rds"))},error = function(e) {return(NULL)})
} else { sc1conf_atac     <- NULL
          sc1def_atac      <- NULL
          sc1gene_atac     <- NULL
          sc1meta_atac     <- NULL
          sc1fragmentpaths <- NULL
          sc1annotation    <- NULL
          sc1peaks         <- NULL
          sc1links         <- NULL
        }

if (file.exists(file.path(dir_inputs, "markergenes_lists.parquet"))) {
  markers_list <- file.path(dir_inputs, "markergenes_lists.parquet")
} else {
  markers_list <- NULL 
}

assays <- c("RNA") # still unclear if I am using this for anything
assays_vec <- unique(sc1conf$assay)

tab_registry <- list()

register_tab <- function(id, title, ui, server) {

  fn_args <- names(formals(server))
  if (is.null(fn_args)) fn_args <- character()

  has_id <- "id" %in% fn_args
  has_input <- "input" %in% fn_args
  has_output <- "output" %in% fn_args
  has_session <- "session" %in% fn_args

  if (!isTRUE(has_id)) {
    stop("register_tab: server function must have argument id for tab: ", id)
  }

  if (isTRUE(has_input) || isTRUE(has_output) || isTRUE(has_session)) {
    warning(
      paste(
        "Tab", id, "server declares input and or output and or session as arguments.",
        "For Shiny module style, server should be function(id, ...) and call moduleServer inside.",
        "This tab will still be registered, but consider updating the signature."
      ),
      call. = FALSE
    )
  }

  tab_registry[[id]] <<- list(
    title  = title,
    ui     = ui,
    server = server
  )
}

get_tab_ids <- function(enabled_tabs = NULL) {
  all_ids <- names(tab_registry)
  if (is.null(enabled_tabs) || length(enabled_tabs) == 0) all_ids else intersect(enabled_tabs, all_ids)
}

get_app_dir <- function() {
  ofile <- tryCatch({sys.frame(1)$ofile}, error = function(e) {retunr(NULL)})
  if (!is.null(ofile) && is.character(ofile) && nzchar(ofile)) {
    return(normalizePath(dirname(ofile), winslash = "/", mustWork = TRUE))
  }

  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) == 1) {
    f <- sub("^--file=", "", file_arg)
    if (nzchar(f) && file.exists(f)) {
      return(normalizePath(dirname(f), winslash = "/", mustWork = TRUE))
    }
  }

  normalizePath(getwd(), winslash = "/", mustWork = TRUE)
}

app_dir <- get_app_dir()
modules_dir <- file.path(app_dir, "modules")

if (!dir.exists(modules_dir)) {
  stop("Modules dir not found: ", modules_dir, " Current working directory: ", getwd())
}

for (f in list.files(modules_dir, full.names = TRUE, pattern = "\\.[Rr]$")) {
  message("Sourcing module: ", basename(f))
  tryCatch(
    {source(f, local = environment())},
    error = function(e) {
      warning(
        paste0("Skipping module due to error: ", basename(f), " | ", conditionMessage(e)),
        call. = FALSE
      )
    }
  )
}


if (length(tab_registry) == 0) {
  warning(
    paste(
      "No modules registered any tabs.",
      "This usually means module files were not sourced correctly",
      "or register_tab() was not called.",
      "Check modules/ and module file names."
    ),
    call. = FALSE
  )
}

enabled_tabs <- c("bubble_heatmap", "cellinfo_cellinfo", "cellinfo_geneexpr", "cellinfo3D_cellinfo3D", "cellinfo3D_geneexpr3D", "genecoex", "proportions", "pseudobulk", "violin_boxplot")

missing_tabs <- setdiff(enabled_tabs, names(tab_registry))
if (length(missing_tabs) > 0) {
  warning(
    paste(
      "The following requested tabs were not found:",
      paste(missing_tabs, collapse = ", "),
      "They will be ignored. Make sure the registry in the modules matches your requested tab"
    ),
    call. = FALSE
  )
}

tab_ids <- get_tab_ids(enabled_tabs)

tab_panels <- lapply(tab_ids, function(k) {
  tabPanel(
    tab_registry[[k]]$title,
    tab_registry[[k]]$ui(id = k, sc1conf = sc1conf, sc1def = sc1def)
  )
})



 ui <- fluidPage( theme = shinytheme("cerulean"),
      tags$head(
        tags$style(HTML(".shiny-output-error-validation {color: red; font-weight: bold;}")),
        tags$style(HTML(".navbar{min-height:36px;} .navbar-default .navbar-nav>li>a{padding-top:8px;padding-bottom:8px;font-size:13px;font-weight:bold;} .navbar-default .navbar-brand{padding-top:8px;padding-bottom:8px;font-size:13px;font-weight:bold;border-right:1px solid rgba(255,255,255,0.3);margin-right:4px;} .navbar-collapse{padding-top:0;padding-bottom:0;}"))
      ),
      do.call(navbarPage, c(list(title = app_title), tab_panels)),
      tags$hr(),
      tags$p(
        style = "font-size: 90%; color: #666;",
        em(
          "This application was generated using ShinyCellModular. ",
          "Tabs are dynamically loaded from modular components.",
          "Monash Genomics and Bioinformatics Platform. ShinyCellModular: ShinyCell Package Customized by MGBP v.1 Date: Jan 2026"
        )
      ),
      br(), br(), br(), br(), br()
    )
  
 
   
    
    
  


server <- function(input, output, session) {
  lapply(tab_ids, function(k) {

    srv <- tab_registry[[k]]$server

    args_to_pass <- list(
      id = k,
      sc1conf = sc1conf,
      sc1meta = sc1meta,
      sc1gene = sc1gene,
      sc1def  = sc1def,
      sc1conf_atac     = sc1conf_atac,
      sc1def_atac      = sc1def_atac,
      sc1gene_atac     = sc1gene_atac,
      sc1meta_atac     = sc1meta_atac,
      sc1fragmentpaths = sc1fragmentpaths,
      sc1annotation    = sc1annotation,
      sc1peaks         = sc1peaks,
      sc1links         = sc1links,
      markers_list = markers_list,
      assays = assays,
      dir_inputs = dir_inputs
    )

    keep <- intersect(names(args_to_pass), names(formals(srv)))
    do.call(srv, args_to_pass[keep])
  })
}


shinyApp(ui, server)

